#!/bin/bash

set -ex

# Clean the Godep workspace to make sure everything is rebuilt from scratch.
pkg='./Godeps/_workspace/pkg'
[ -d "$pkg" ] && rm -R "$pkg"

# Assemble and install the executable.
godep go install -v
